Upload the library binary to prod or snapshots remote accordingly

diff --git a/libs-conan-upload/action.yml b/libs-conan-upload/action.yml
--- a/libs-conan-upload/action.yml
+++ b/libs-conan-upload/action.yml
@@ -15,7 +15,7 @@ runs:
       shell: bash
 
     - name: Assert info detected
-      if: ${{env.cmake_found != 'True' || env.conan_found != 'True' || env.library == ''}}
+      if: ${{env.cmake_found != 'True' || env.conan_found != 'True' || env.library == '' || (env.is_snapshot != 'True' && env.is_snapshot != 'False')}}
       uses: actions/github-script@v7
       with:
         script: core.setFailed('Library not detected in conanfile, or CMakeLists.txt is missing, or conanfile is missing')
@@ -25,6 +25,16 @@ runs:
       working-directory: ${{inputs.working-directory}}
       shell: bash
 
-    - name: Conan upload
-      run: conan upload ${{env.library}} -r neboskreb-conan --force
+    - name: Conan upload to the production repo
+      if: ${{env.is_snapshot == 'False'}}
+      run: conan upload ${{env.library}} -r neboskreb-conan
+      shell: bash
+
+    - name: Conan upload to snapshots repo
+      # Also cleanup the intermediate revisions to minimize the space waste
+      if: ${{env.is_snapshot == 'True'}}
+      run: |
+        conan remove "*/*#!latest" -c 
+        conan upload ${{env.library}} -r neboskreb-snapshots --force
+        conan remove "*/*#!latest" -c -r neboskreb-snapshots
       shell: bash
